### ISSUE TITLE
Grid入门完全指南-理论篇

### ISSUE THREAD

**Issue by NikoManiac** [NikoManiac/Vimer#22]
# Grid入门完全指南-理论篇

## Todo

1. Grid布局对子子代的影响
2. grid | inline-grid的区别
3. grid-template-columns：Can we mix line-name and track size in one grid-template-columns
4. Rapeat() stantand 
5. difference Explicit Grids with Implicit Grids

## 概述

Grid布局是一种二维布局方式，关注于多行多列。

### 名词解析

*以下名词在理解Grid布局中，十分重要*

#### Grid Container

应用`display: grid`的元素，可以理解成所有Grid Items的父元素，例如下面container节点

```html
<div class="container">
  <div class="item item-1"></div>
  <div class="item item-2"></div>
  <div class="item item-3"></div>
</div>
```

#### Grid Items

所有container节点的*直接*子节点，例如item元素，在这里需要强调是直接子节点，`sub-item`就不属于Grid Items了

```html
<div class="container">
  <div class="item"></div> 
  <div class="item">
  	<p class="sub-item"></p>
  </div>
  <div class="item"></div>
</div>
```

#### Grid Line

垂直或者水平的分割线。

#### Grid Track

两条相邻的Grid Line之间的空间，由此可见可能是水平的，有可能是垂直的。

#### Grid Cell

可以理解成网格中的一个单元格

#### Grid Area

四条Grid Line围成的区域

#### fr

Grid布局的一种单位形式，可以计算当前Grid剩余的空间，然后按比例自动计算出当前row或者column的Grid Track。而且可以混入具体数值的计算。

// todo： 与百分比和分数的混合计算。

```css
// 每一个fr都是1/3
.container {
  grid-template-columns: 1fr 1fr 1fr;
}

// 减去50px之后的1/3
.container {
  grid-template-columns: 1fr 50px 1fr 1fr;
}
```

### 设置在Grid Container上的属性

```css
// 语法：
// grid: 块级grid
// inline-grid: 内联grid
.container {
  display: grid | inline-grid;
}
```

Container属性一览

- Grid-template-columns
- Grid-template-rows
- Grid-template-areas
- 合体：grid-tamplate
- Grid-column-gap
- Grid-row-gap
- 合体Grid-gap
- Justify-items
- Align-items
- 合体：Place-items
- Justify-content
- Align-content
- 合体：Place-content
- Grid-auto-columns
- Grid-auto-rows
- Grid-auto-flow
- Grid

*******

###### Grid-template-columns和Grid-template-rows

**Values**

- **<track-size>** - 可以是正常的px这种单位，也可以是百分比，也可以是fr。
- **<line-name>** - 可以随意自定的line名，line-name我们会在[Grid Items](#grid-items)属性中使用到。

```css
.container {
  grid-template-columns: <track-size> ... | <line-name> <track-size> ...;
  grid-template-rows: <track-size> ... | <line-name> <track-size> ...;
}

// 栗子：
.container {
  grid-template-columns: 40px 50px auto 50px 40px;
  grid-template-rows: 25% 100px auto;
}
```

![img](https://css-tricks.com/wp-content/uploads/2018/11/template-columns-rows-01.svg)

```css
// line-name栗子，需要使用方括号
.container {
  grid-template-columns: [first] 40px [line2] 50px [line3] auto [col4-start] 50px [five] 40px [end];
  grid-template-rows: [row1-start] 25% [row1-end] 100px [third-line] auto [last-line];
}

// 如果含有重复的部分，我们也可以使用repeat()
.container {
  grid-template-columns: repeat(3, 20px [col-start]);
}
// 等价于，但是注意，这里是缺少了第一个line-name的
.container {
  grid-template-columns: 20px [col-start] 20px [col-start] 20px [col-start];
}
```

![Grid with user named lines](https://css-tricks.com/wp-content/uploads/2018/11/template-column-rows-02.svg)

****

###### grid-template-areas

在container上定义一个Grid area，并通过定义的name，在Grid Items中的grid-area中使用。

**Values**

- **<grid-area-name>** - 指定的Grid Area的名称
- **.** - 空的Grid Cell
- **none** - 没有Grid Cell定义

```css
// 语法
.container {
  grid-template-areas: 
    "<grid-area-name> | . | none | ..."
    "...";
}

// 🌰：
.container {
  display: grid;
  grid-template-columns: 50px 50px 50px 50px;
  grid-template-rows: auto;
  grid-template-areas: 
    "header header header header"
    "main main . sidebar"
    "footer footer footer footer";
}

.item-a {
  grid-area: header;
}
.item-b {
  grid-area: main;
}
.item-c {
  grid-area: sidebar;
}
.item-d {
  grid-area: footer;
}
```

![Example of grid-template-areas](https://css-tricks.com/wp-content/uploads/2018/11/dddgrid-template-areas.svg)

****

###### grid-tamplate

太复杂...

###### grid-column-gap / grid-row-gap和grid-gap

定义Grid Line的宽度

```
// 语法：
.container {
  grid-column-gap: <line-size>;
  grid-row-gap: <line-size>;
}
或者：
.container {
  grid-gap: <grid-row-gap> <grid-column-gap>;
}

// 🌰：
.container {
  grid-template-columns: 100px 50px 100px;
  grid-template-rows: 80px auto 80px; 
  grid-column-gap: 10px;
  grid-row-gap: 15px;
}
```

![Example of grid-column-gap and grid-row-gap](https://css-tricks.com/wp-content/uploads/2018/11/dddgrid-gap.svg)

****

###### Justify-items / Align-items和place-items

Justify-items / Align-items都定义了Grid Cell内部的items的对齐方式，只不过，Justify-items规定了inline元素，而Align-items规定了block元素。而place-items是Justify-items / Align-items的合集。

了解过flex布局，应该很好理解。

**Values**

- **start** - 在Cell中，从start边对齐
- **end** - 在Cell中，从end边对齐
- **center** - 在Cell中，居中
- **stretch** - 在Cell中，填满

```css
.container {
  align-items: center;
}
```

![Example of align-items set to center](https://css-tricks.com/wp-content/uploads/2018/11/align-items-center.svg)

****

###### Justify-content / Align-content和place-content

有时候，我们在Grid Container内部定义的Grid的大小，也许加起来并没有外部的Container大，例如我们用px布局的时候。这时候，我们可以设置内部Grid的对齐方式。

 其用法语与Justify-items / Align-items和place-items相似，只不过可选的value增加了几个：

- **space-around** - 均匀的在Grid Item中放置，与start边和end边有间隔。
- **space-between** - 均匀的在Grid Item中放置，与start边和end边没有间隔。
- **space-evenly** - start边-grid items-end边间隔大小相等。

```css
// 🌰：
.container {
  justify-content: space-evenly;	
}
```

![Example of justify-content set to space-evenly](https://css-tricks.com/wp-content/uploads/2018/11/justify-content-space-evenly.svg)

****

###### grid-auto-columns /  grid-auto-rows和grid-auto-flow

grid-auto-* 系列，其实是与gird-template-*系列相对应。在此之前，我们需要理解Explicit Grids语Implicit Grids的不同。

<h3 id='grid-items'>Grid Items属性</h3>

*Grid Items中的属性主要含义是怎么去使用在Grid Container中定义的Cell或者Area，这里需要注意的是，`float`, `display: inline-block`, `display: table-cell`, `vertical-align` 和 `column-*` 在Grid Items中将会不起作用*

Items属性一览：

- Grid-column-start
- Grid-column-end
- 合体：grid-column
- Grid-row-start
- Grid-row-end
- 合体：grid-row
- 终极合体：grid-area
- Justify-self
- Align-self
- 合体：place-self

****

###### grid-column-start  / grid-column-end / grid-row-start / grid-row-end和 grid-column / grid-row

// todo： how to compule the area when value is auto

**Values**

- **<line>** - 可以是Grid Line的number或者name。
- **span <number>** - 跨越number个Grid tracks。
- **span <name>** - 跨越至line-name所在的line。
- **auto** - 暂无。

```css
// 语法
.item {
  grid-column-start: <number> | <name> | span <number> | span <name> | auto;
  grid-column-end: <number> | <name> | span <number> | span <name> | auto;
  grid-row-start: <number> | <name> | span <number> | span <name> | auto;
  grid-row-end: <number> | <name> | span <number> | span <name> | auto;
}

// 🌰：
.item-a {
  grid-column-start: 2;
  grid-column-end: five;
  grid-row-start: row1-start
  grid-row-end: 3;
}
```

![Example of grid-row/column-start/end](https://css-tricks.com/wp-content/uploads/2018/11/grid-column-row-start-end-01.svg)

```
// 🌰🌰：
.item-b {
  grid-column-start: 1;
  grid-column-end: span col4-start;
  grid-row-start: 2
  grid-row-end: span 2
}
```

![Example of grid-row/column-start/end](https://css-tricks.com/wp-content/uploads/2018/11/grid-column-row-start-end-02.svg)

****

###### grid-area

**Values**

- **<name>** - 我们在container属性中，使用grid-tamplate-area定义的area。
- **<row-start> / <column-start> / <row-end> / <column-end>** - `grid-row-start` + `grid-column-start` + `grid-row-end` + `grid-column-end`的简写形式，可以说数字或者line-name。

```css
// 语法：
.item {
  grid-area: <name> | <row-start> / <column-start> / <row-end> / <column-end>;
}

// 栗子：
.item-d {
  grid-area: header;
}
// 再来一个栗子：
.item-d {
  grid-area: 1 / col4-start / last-line / 6;
}
```

![Example of grid-area](https://css-tricks.com/wp-content/uploads/2018/11/grid-area.svg)

#### 【其他】start和end的来源

如果你对属性中的start和end不够理解，可以阅读大漠老师的文章[理解SS的逻辑属性与值](https://www.w3cplus.com/css/understanding-logical-properties-values.html)。

简单来说就是：W3C的CSS工作组，希望在不同的书写模式中，以抽取出共性的抽象概念（如开始位置，或行），这些逻辑抽象概念需要在不同书写模式下映射到左或右、上或下等物理的概念上。

很简单的例子：阿拉伯语需要从右向左书写，我们之前的一些写法，例如 `*-left`属性就会变得费解，没有逻辑。

## Grid Area 

grid area可以分别由container和items定义：

container需要使用grid-template-area定义，然后在grid-area中世界使用名字。

而在items中直接定义，则需要`grid-row-start` + `grid-column-start` + `grid-row-end` + `grid-column-end`的简写形式。

## 【心痛】caniuse

![image-20190407161030135](/Users/Ingram/Library/Application Support/typora-user-images/image-20190407161030135.png)

## 与flexbox布局的对比

众所周知，Flexbox布局是一维的布局，而Grid布局是二维布局。

看两者提供的功能，其实是有冲突的，但是实际使用中，二者结合起来会非常的强大。

flexbox的流式布局可以非常便利的解决传统布局模式中的一些痛点，比如说某个div居中（此处应该有笑声）。但是对于更复杂的布局，还是有一些力不从心。至少从我目前不多的使用场景中，大多都是用来做一行内的布局，虽然它也提供了`flex-wrap: wrap`这样的能力。

另外，flex布局对响应式设计也十分友好，其在一维方向对伸缩性的控制，可以很好的在PC和移动两端切换。

所以，我们可以使用Flexbox做局部的布局设计。正好不影响我们整体的layout用grid。

## CSS布局的趋势

三维布局是不是不是程序员应该考虑的事情～
